version: "3.9"
services:
  nginx:
    build: ./docker/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - nuxt

  nuxt:
    build:
      context: .
      dockerfile: ./docker/nuxt/Dockerfile
    container_name: nuxt
    ports:
      - "3000:3000"
